### ISSUE TITLE
Where can I find the application binary?

### ISSUE THREAD

**Issue by qudarr** [PraneetNeuro/Patchman#2]
Hi Praneet, 

I am relatively new to GitHub. Where can I find the compiled binary?
I don't have xCode on my machine.

**Comment by praneet-suresh** [comment]
https://github.com/PraneetNeuro/Patchman/releases/download/v2.0.2/Patchman.app.zip

**Comment by qudarr** [comment]
Thanks for reacting so quickly. MacOS is warning me about malware contained in the app.

![CleanShot 2021-05-10 at 15 32 14](https://user-images.githubusercontent.com/30973564/117667162-e9313080-b1a4-11eb-9e38-13c04f316d74.png)

**Comment by praneet-suresh** [comment]
Hey, there's nothing to worry about! Since the app isn't distributed through the Mac App Store, Macs usually tend to warn about potential malware, but to go ahead you can do this: Right-click the application, select “Get Info”, and check the “Override Malware Protection” box. Enter your password to open the application.
